# Generated by Django 4.2.3 on 2024-03-07 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Myadmin',
            new_name='user',
        ),
    ]
